# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d1776c598a81c0b49603cba165b92ee"
name = "Configurator"
application_url = "https://shopify-app-nine-tau.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_products"

[auth]
redirect_urls = [ "https://shopify-app-nine-tau.vercel.app/api/auth/callback" ]
